import { m } from './i18n';

/**
 * Pixel-preset catalog — the single source of truth (spec § 6.5).
 * The DB stores only the `id`; the artwork is static in
 * `/public/avatars/{id}.svg`, generated by `npm run gen:assets`
 * (DiceBear, `pixel-art` style).
 *
 * Labels are cartridge-era call signs from a character-select screen, not
 * portrait descriptions. The difference matters: portraits are generated from
 * a `seed`, so a descriptive name like "Redhead in a cap" would eventually
 * diverge from the picture, while a call sign promises nothing about it. The
 * label is read aloud by screen readers and shown in the picker, so it must
 * not lie. Localized labels live in the i18n dictionaries.
 *
 * Call signs are invented, not taken from real games: existing titles and
 * character names are someone else's trademarks. For the same reason they are
 * not tied to gender — the generator decides which portrait a call sign gets.
 *
 * `id` values must never change — the DB references them.
 */
export const AVATAR_IDS = [
  'pixel-01',
  'pixel-02',
  'pixel-03',
  'pixel-04',
  'pixel-05',
  'pixel-06',
  'pixel-07',
  'pixel-08',
  'pixel-09',
  'pixel-10',
  'pixel-11',
  'pixel-12',
  'pixel-13',
  'pixel-14',
  'pixel-15',
  'pixel-16',
  'pixel-17',
  'pixel-18',
  'pixel-19',
  'pixel-20',
  'pixel-21',
  'pixel-22',
  'pixel-23',
  'pixel-24',
] as const;

export type AvatarId = (typeof AVATAR_IDS)[number];

export const AVATARS: ReadonlyArray<{ id: AvatarId; label: string }> = AVATAR_IDS.map((id) => ({
  id,
  label: m.avatars[id],
}));

export const isAvatarId = (v: string): v is AvatarId =>
  (AVATAR_IDS as readonly string[]).includes(v);

export const avatarSrc = (id: string): string => `/avatars/${id}.svg`;

export const avatarLabel = (id: string): string =>
  isAvatarId(id) ? m.avatars[id] : m.avatars.fallback;

/** A random avatar among the free ones; if none are free — any (spec § 6.5). */
export function randomAvatarId(taken: readonly string[] = []): AvatarId {
  const free = AVATAR_IDS.filter((id) => !taken.includes(id));
  const pool = free.length > 0 ? free : AVATAR_IDS;
  return pool[Math.floor(Math.random() * pool.length)];
}
