/**
 * GENERATED by `npm run gen:icons` — do not edit by hand.
 *
 * pixelarticons icons (https://pixelarticons.com), MIT license.
 * 24×24 grid, integer coordinates — see `components/ui/icon.tsx`.
 */

/** Shared grid of the icon set: crispEdges rendering relies on it. */
export const ICON_VIEWBOX = '0 0 24 24';

export const ICON_PATHS = {
  /** pixelarticons: fire */
  flame: [
    'M9 2h2v4H9zM7 6h2v2H7zM5 8h2v2H5zm8 2h2v2h-2zm2-2h2v2h-2zm2 2h2v2h-2zm2 2h2v6h-2zM3 10h2v8H3zm8-4h2v4h-2zm6 12h2v2h-2zM7 20h10v2H7zm-2-2h2v2H5zm4-2h6v4H9z',
    'M11 14h2v3h-2z',
  ],
  /** pixelarticons: trophy */
  trophy: [
    'M16 17H13V19H15V21H9V19H11V17H8V15H16V17ZM18 5H22V11H20V7H18V11H20V13H18V15H16V5H8V15H6V13H4V11H6V7H4V11H2V5H6V3H18V5Z',
  ],
  /** pixelarticons: clock */
  clock: [
    'M6 2h12v2H6zM2 6h2v12H2zm18 0h2v12h-2zm-2-2h2v2h-2zM4 4h2v2H4zm2 18h12v-2H6zm12-2h2v-2h-2zM4 20h2v-2H4zm7-14h2v7h-2zm2 7h2v2h-2zm2 2h2v2h-2z',
  ],
  /** pixelarticons: comment-text */
  hint: [
    'M4 2h16v2H4zm0 14h14v2H4zm2-6h6v2H6zm0-4h12v2H6zM2 4h2v12H2zm18 0h2v18h-2zm-2 14h2v2h-2z',
  ],
  /** pixelarticons: check */
  check: [
    'M10 18H8v-2h2v2Zm-2-2H6v-2h2v2Zm4-2v2h-2v-2h2Zm-6 0H4v-2h2v2Zm8 0h-2v-2h2v2Zm2-2h-2v-2h2v2Zm2-2h-2V8h2v2Zm2-2h-2V6h2v2Z',
  ],
  /** pixelarticons: plus */
  plus: [
    'M13 11h7v2h-7v7h-2v-7H4v-2h7V4h2v7Z',
  ],
  /** pixelarticons: minus */
  minus: [
    'M4 11h16v2H4z',
  ],
  /** pixelarticons: play */
  play: [
    'M15 11h-2V9h2zm0 4h-2v-2h2zm-2 2h-2v-2h2zm0-8h-2V7h2zm-2-2H9V5h2zM9 21H7V3h2zm6-8h2v-2h-2zm-6 4h2v2H9z',
  ],
  /** pixelarticons: flag */
  finish: [
    'M4 2h2v20H4z',
    'M4 4h16v2H4zm12 2h2v2h-2zm-2 2h2v2h-2zm2 2h2v2h-2zM4 12h16v2H4z',
  ],
  /** pixelarticons: human-arms-down */
  walk: [
    'M10 2h4v4h-4zM7 7h10v2H7zm2 2h2v7H9zm4 0h2v7h-2zm-4 7h2v6H9zm4 0h2v6h-2zm-2-2h2v2h-2zM5 9h2v2H5zm-2 2h2v2H3zm14-2h2v2h-2zm2 2h2v2h-2z',
  ],
  /** pixelarticons: star */
  star: [
    'M5 20H8V22H3V16H5V20ZM21 22H16V20H19V16H21V22ZM10 20H8V18H10V20ZM16 20H14V18H16V20ZM14 18H10V16H14V18ZM7 16H5V13H7V16ZM19 16H17V13H19V16ZM5 13H3V11H5V13ZM21 13H19V11H21V13ZM9 9H3V11H1V7H9V9ZM23 11H21V9H15V7H23V11ZM11 7H9V3H11V7ZM15 7H13V3H15V7ZM13 3H11V1H13V3Z',
  ],
  /** pixelarticons: map-pin */
  pin: [
    'M7 2h10v2H7zM5 4h2v2H5zm14 0h-2v2h2zM7 17h2v2H7zm2 2h2v2H9zm6-2h2v2h-2zm-2 2h2v2h-2zm-2 2h2v2h-2zm-6-7h2v3H5zm12 0h2v3h-2zM3 6h2v8H3zm18 0h-2v8h2zM10 6h4v2h-4zM8 8h2v4H8zm2 4h4v2h-4zm4-4h2v4h-2z',
  ],
  /** pixelarticons: chevron-down */
  chevronDown: [
    'M13 16h-2v-2h2v2Zm-2-2H9v-2h2v2Zm4 0h-2v-2h2v2Zm-6-2H7v-2h2v2Zm8 0h-2v-2h2v2ZM7 10H5V8h2v2Zm12 0h-2V8h2v2Z',
  ],
  /** pixelarticons: calendar-range */
  calendar: [
    'M5 4h14v2H5zm0 16h14v2H5zM3 10h2v10H3zm0-4h2v2H3zm16 0h2v2h-2zm0 4h2v10h-2zM3 8h18v2H3zm12-6h2v2h-2zM7 2h2v2H7zm4 10h6v2h-6zm-4 4h6v2H7z',
  ],
  /** pixelarticons: settings-cog-2 */
  gear: [
    'M18 2h2v2h-2zM4 2h2v2H4zm16 20h-2v-2h2zM4 22h2v-2H4zM20 4h2v2h-2zM6 4h4v2H6zm12 16h-4v-2h4zM6 20h4v-2H6zM18 6h2v4h-2zM4 6h2v4H4zm16 12h-2v-4h2zM4 18h2v-4H4zM14 4h4v2h-4zM2 4h2v2H2zm20 16h-2v-2h2zM2 20h2v-2H2z',
    'M8 2h2v4H8zm0 20h2v-4H8z',
    'M8 2h8v2H8zm0 20h8v-2H8zM2 8h2v8H2zm20 8h-2V8h2z',
    'M20 8h2v4h-2zM10 8h4v2h-4zm-2 2h2v4H8zm2 4h4v2h-4zm4-4h2v4h-2z',
  ],
  /** pixelarticons: send */
  send: [
    'M4 19h4v2H2v-8h2v6Zm8 0H8v-2h4v2Zm4-2h-4v-2h4v2Zm4-2h-4v-2h4v2Zm-10-2H4v-2h6v2Zm12 0h-2v-2h2v2ZM8 5H4v6H2V3h6v2Zm12 6h-4V9h4v2Zm-4-2h-4V7h4v2Zm-4-2H8V5h4v2Z',
  ],
  /** pixelarticons: car */
  car: [
    'M4 13h6v2H4zm10 0h6v2h-6zM4 17h6v2H4zm10 0h6v2h-6zM2 15h4v2H2zm6 0h8v2H8zm10 0h4v2h-4zm4-4h2v4h-2zm-6-4h2v2h-2zM4 5h12v2H4zm-4 6h2v4H0zm12-2h10v2H12zM2 7h2v4H2zm8 0h2v2h-2z',
  ],
  /** pixelarticons: pencil */
  edit: [
    'M4 16H6V18H8V20H10V22H2V14H4V16ZM12 20H10V18H12V20ZM14 18H12V16H14V18ZM10 16H8V14H10V16ZM16 16H14V14H16V16ZM6 14H4V12H6V14ZM12 14H10V12H12V14ZM18 14H16V12H18V14ZM8 12H6V10H8V12ZM14 12H12V10H14V12ZM20 12H18V10H20V12ZM10 10H8V8H10V10ZM18 10H16V8H18V10ZM22 10H20V8H22V10ZM12 8H10V6H12V8ZM16 8H14V6H16V8ZM20 8H18V6H20V8ZM14 6H12V4H14V6ZM18 6H16V4H18V6ZM16 4H14V2H16V4Z',
  ],
  /** pixelarticons: trash */
  trash: [
    'M18 22H6V20H18V22ZM9 6H15V4H17V6H22V8H20V20H18V8H6V20H4V8H2V6H7V4H9V6ZM15 4H9V2H15V4Z',
  ],
  /** pixelarticons: power */
  power: [
    'M6 20h12v2H6zM18 6h2v2h-2zM4 6h2v2H4zm2-2h2v2H6zm10 0h2v2h-2zM4 18h2v2H4zm14 0h2v2h-2zM2 8h2v10H2zm18 0h2v10h-2zm-9-6h2v9h-2z',
  ],
  /** pixelarticons: power-off */
  powerOff: [
    'M6 20h10v2H6zM18 6h2v2h-2zm-2-2h2v2h-2zM4 18h2v2H4zm14 0h2v2h-2zM2 8h2v10H2zm18 0h2v8h-2zm-9-6h2v6h-2zm9 18h2v2h-2zm-4-4h2v2h-2zm-2-2h2v2h-2zm-2-2h2v2h-2zm-2-2h2v2h-2zM8 8h2v2H8zM6 6h2v2H6zM4 4h2v2H4zM2 2h2v2H2z',
  ],
  /** custom, scripts/icons/bird.svg */
  bird: [
    'M11 4h6v2h-6zM11 6h2v2h-2zM15 6h2v2h-2zM17 7h3v2h-3zM5 8h4v2H5zM9 8h8v2H9zM8 10h9v2H8zM9 12h7v2H9zM10 14h5v2h-5zM10 16h2v2h-2zM13 16h2v2h-2z',
  ],
  /** custom, scripts/icons/boot.svg */
  boot: [
    'M8 3h6v8H8zM8 11h12v4H8zM14 9h4v2h-4zM6 15h14v3H6zM6 18h2v2H6zM10 18h2v2h-2zM14 18h2v2h-2zM18 18h2v2h-2z',
  ],
  /** custom, scripts/icons/calendar-check.svg */
  calendarCheck: [
    'M7 3h2v4H7zM15 3h2v4h-2zM4 5h16v4H4zM4 9h2v10H4zM18 9h2v10h-2zM4 19h16v2H4zM7 13h2v2H7zM9 15h2v2H9zM11 13h2v2h-2zM13 11h2v2h-2z',
  ],
  /** custom, scripts/icons/ember.svg */
  ember: [
    'M11 3h2v2h-2zM10 5h4v2h-4zM9 7h6v2H9zM8 9h8v2H8zM8 11h3v2H8zM13 11h3v2h-3zM9 13h6v2H9zM5 17h14v2H5zM7 19h2v2H7zM15 19h2v2h-2z',
  ],
  /** custom, scripts/icons/flames.svg */
  flames: [
    'M13 3h2v2h-2zM12 5h4v2h-4zM11 7h6v2h-6zM6 9h2v2H6zM5 11h4v4H5zM10 9h8v6h-8zM6 15h13v3H6zM8 18h9v2H8z',
  ],
  /** custom, scripts/icons/footprint.svg */
  footprint: [
    'M8 3h8v2H8zM6 5h12v4H6zM7 9h10v2H7zM8 14h8v2H8zM9 16h6v2H9z',
  ],
  /** custom, scripts/icons/gauge-max.svg */
  gaugeMax: [
    'M8 4h8v2H8zM5 6h3v2H5zM16 6h3v2h-3zM4 8h2v6H4zM18 8h2v6h-2zM4 14h16v2H4zM12 10h5v2h-5zM10 12h4v2h-4z',
  ],
  /** custom, scripts/icons/gauge.svg */
  gauge: [
    'M8 4h8v2H8zM5 6h3v2H5zM16 6h3v2h-3zM4 8h2v6H4zM18 8h2v6h-2zM4 14h16v2H4zM11 7h2v6h-2zM9 12h6v2H9z',
  ],
  /** custom, scripts/icons/lightning.svg */
  lightning: [
    'M14 3h4v2h-4zM13 5h4v2h-4zM12 7h4v2h-4zM10 9h8v2h-8zM8 11h8v2H8zM9 13h4v2H9zM8 15h3v2H8zM7 17h2v2H7zM6 19h2v2H6z',
  ],
  /** custom, scripts/icons/medal.svg */
  medal: [
    'M7 3h4v5H7zM13 3h4v5h-4zM9 8h6v2H9zM7 10h2v4H7zM15 10h2v4h-2zM9 14h6v2H9zM11 11h2v2h-2z',
  ],
  /** custom, scripts/icons/milestone.svg */
  milestone: [
    'M6 3h12v2H6zM6 5h2v4H6zM16 5h2v4h-2zM6 9h12v2H6zM11 6h2v2h-2zM11 11h2v8h-2zM8 19h8v2H8z',
  ],
  /** custom, scripts/icons/owl.svg */
  owl: [
    'M5 4h3v2H5zM16 4h3v2h-3zM5 6h14v3H5zM5 9h2v3H5zM10 9h4v3h-4zM17 9h2v3h-2zM5 12h14v4H5zM7 16h3v2H7zM14 16h3v2h-3z',
  ],
  /** custom, scripts/icons/signpost.svg */
  signpost: [
    'M4 4h12v6H4zM16 5h2v4h-2zM18 6h2v2h-2zM11 10h2v9h-2zM8 19h8v2H8z',
  ],
  /** custom, scripts/icons/stones.svg */
  stones: [
    'M9 5h6v4H9zM7 11h10v4H7zM5 17h14v4H5z',
  ],
  /** custom, scripts/icons/sun.svg */
  sun: [
    'M8 8h8v8H8zM11 3h2v3h-2zM11 18h2v3h-2zM3 11h3v2H3zM18 11h3v2h-3zM5 5h2v2H5zM17 5h2v2h-2zM5 17h2v2H5zM17 17h2v2h-2z',
  ],
  /** custom, scripts/icons/sunset.svg */
  sunset: [
    'M9 6h6v2H9zM8 8h8v4H8zM11 2h2v2h-2zM4 4h2v2H4zM18 4h2v2h-2zM3 12h18v2H3zM6 16h4v2H6zM14 16h4v2h-4z',
  ],
  /** custom, scripts/icons/tally.svg */
  tally: [
    'M5 4h2v14H5zM9 4h2v14H9zM13 4h2v14h-2zM17 4h2v14h-2zM3 15h4v2H3zM7 12h4v2H7zM11 9h4v2h-4zM15 6h4v2h-4z',
  ],
} as const;

export type IconName = keyof typeof ICON_PATHS;
