#!/usr/bin/env node
/**
 * TeamWalk icon set generator (a single set, no icon fonts).
 *
 * Source — pixelarticons (https://pixelarticons.com, MIT, `pixelarticons`
 * package): ready-made 24×24 pixel icons on a 1×1 grid. The set used to be
 * hand-drawn as ASCII matrices in `gen-avatars.mjs` — a homegrown 14-icon
 * wheel that had to be extended for every new button.
 *
 * Builds `lib/icons.generated.ts` — a "name → array of path d" map. The data
 * is inlined into the bundle rather than served from `/public`: icons render
 * as <svg> with `fill="currentColor"` and inherit the text color (in <img>,
 * currentColor resolves to black — icons vanished on the app's dark background).
 *
 * Run: `npm run gen:icons`.
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'node_modules', 'pixelarticons', 'svg');
const OUT = join(ROOT, 'lib', 'icons.generated.ts');

/**
 * Code name → pixelarticons file.
 *
 * Left side is the UI role, right side is the set's file: if a better icon
 * turns up for a role, one line changes instead of every call site.
 */
const MAP = {
  /** Consecutive-day streak. */
  flame: 'fire',
  /** Personal record, achievement, and the podium cup. */
  trophy: 'trophy',
  /** Time, waiting, "treadmill busy". */
  clock: 'clock',
  /** NPC line in the hints feed. */
  hint: 'comment-text',
  /** Confirmation. */
  check: 'check',
  /** Add a member; increase speed on the walk screen. */
  plus: 'plus',
  /** Decrease speed on the walk screen. */
  minus: 'minus',
  /** Start a walk. */
  play: 'play',
  /** Finish a walk: a finish-line flag, not "stop" — walks are seen through. */
  finish: 'flag',
  /** Walking: headings and empty states. */
  walk: 'human-arms-down',
  /** Achievement list item. */
  star: 'star',
  /** Treadmill on the room map. */
  pin: 'map-pin',
  /** "Expand list" — on the member combobox trigger. */
  chevronDown: 'chevron-down',
  /** Tap-through affordance on the in-progress walk card. */
  arrowRight: 'arrow-right',
  /** Per-user statistics page — on the leaderboard row link. */
  chart: 'chart',
  /** Custom leaderboard period — on the date-range picker button. */
  calendar: 'calendar-range',
  /** "Gearbox" achievement: a cog. */
  gear: 'settings-cog-2',
  /** "In touch" achievement: paper plane — Telegram link. */
  send: 'send',
  /** "Long haul" achievement: 5+ km in one walk. */
  car: 'car',
  /** Edit a treadmill in settings. */
  edit: 'pencil',
  /** Delete a treadmill that has no walks. */
  trash: 'trash',
  /** Re-enable a treadmill. */
  power: 'power',
  /** Disable a treadmill — deactivation instead of deletion. */
  powerOff: 'power-off',
};

/**
 * Hand-drawn icons — `scripts/icons/*.svg`: same 24×24 grid and blocky style
 * as pixelarticons, drawn for specific roles (achievements).
 * Code name is the camelCased file name. Sources live next to the script;
 * only the generated file is consumed.
 */
const CUSTOM_DIR = join(ROOT, 'scripts', 'icons');

/** pixelarticons draws an icon with one or two <path>; keep them in order. */
function extractPaths(svgText, label) {
  const paths = [...svgText.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`No <path d> found in ${label}`);
  return paths;
}

/** Every icon must be 24×24; mixing grids would break stroke weight. */
function assertViewBox(svgText, label) {
  if (!svgText.includes('viewBox="0 0 24 24"')) {
    throw new Error(`${label} is not on a 24×24 grid — the set must be uniform`);
  }
}

const entries = Object.entries(MAP).map(([name, file]) => {
  const svg = readFileSync(join(SRC, `${file}.svg`), 'utf8');
  assertViewBox(svg, `${file}.svg`);
  return [name, `pixelarticons: ${file}`, extractPaths(svg, `${file}.svg`)];
});

for (const file of readdirSync(CUSTOM_DIR).filter((f) => f.endsWith('.svg')).sort()) {
  const name = file.replace(/\.svg$/, '').replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  const svg = readFileSync(join(CUSTOM_DIR, file), 'utf8');
  assertViewBox(svg, `scripts/icons/${file}`);
  entries.push([name, `custom, scripts/icons/${file}`, extractPaths(svg, `scripts/icons/${file}`)]);
}

const body = entries
  .map(([name, source, paths]) => {
    const list = paths.map((d) => `\n    '${d}',`).join('');
    return `  /** ${source} */\n  ${name}: [${list}\n  ],`;
  })
  .join('\n');

const out = `/**
 * GENERATED by \`npm run gen:icons\` — do not edit by hand.
 *
 * pixelarticons icons (https://pixelarticons.com), MIT license.
 * 24×24 grid, integer coordinates — see \`components/ui/icon.tsx\`.
 */

/** Shared grid of the icon set: crispEdges rendering relies on it. */
export const ICON_VIEWBOX = '0 0 24 24';

export const ICON_PATHS = {
${body}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

writeFileSync(OUT, out, 'utf8');
console.log(`Icons: ${entries.length} → lib/icons.generated.ts`);
